apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
      matchLabels:
        app: app
  template:
      metadata:
        labels:
           app: app    

      spec:
          containers:
            - name: app
              image: mahesh032/mahesh5:latest
              env:
                - name: SPRING_DATASOURCE_URL
                  value: "jdbc:mysql://my-sql:3306/ecommerce"
                - name: SPRING_DATASOURCE_USERNAME
                  value: "root"
                -  name: SPRING_DATASOURCE_PASSWORD
                   value: "rootpass"
                -  name: SPRING_JPA_HIBERNATE_DDL_AUTO
                   value: "update"
                - name: SPRING_JPA_SHOW_SQL
                  value: "true"
                - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
                  value: "true"  
              ports:
                - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP