apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sql
  labels:
    app: my-sql
spec:                     
  replicas: 1
  selector:
    matchLabels:
      app: my-sql
  template:
    metadata:
      labels:
        app: my-sql
    spec:
      containers:
        - name: my-sql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpass"
            - name: MYSQL_DATABASE
              value: "ecommerce"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service              
metadata:
  name: my-sql
  labels:
    app: my-sql
spec:
  selector:
    app: my-sql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort
